### ISSUE TITLE
Cannot Export   ("blend_vb": "",         "texcoord_vb": "", ) specific weapons in blender 3.6 using the latest version 7.0

### ISSUE THREAD

**Issue by Khaled-Khedr** [SilentNightSound/GI-Model-Importer-Assets#37]
so here is the error I am assuming its an issue with the fmt file ? 

Python: Traceback (most recent call last):
  File "C:\Users\Dark\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender_3dmigoto_gimi.py", line 2409, in execute
    export_3dmigoto_genshin(self, context, object_name, vb_path, ib_path, fmt_path, self.use_foldername, self.ignore_hidden, self.only_selected, self.no_ramps, self.delete_intermediate, self.credit, Outline_Properties)
  File "C:\Users\Dark\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender_3dmigoto_gimi.py", line 1696, in export_3dmigoto_genshin
    generate_mod_folder(os.path.dirname(vb_path), object_name, no_ramps, delete_intermediate, credit)
  File "C:\Users\Dark\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender_3dmigoto_gimi.py", line 1734, in generate_mod_folder
    with open(os.path.join(path, f"{current_name}{object_classifications[0]}.fmt"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Dark\\Downloads\\Genshin Mods DEV\\Models\\Engulfing\\EngulfingHead.fmt'

**Comment by Khaled-Khedr** [comment]
I download the Engulfing model and everything but I can only seem to export things like skyward harp etc and not empty blend vb and empty textcoordvb weapons.
